added order service and order controller
kriazantseva/book-store-app pull request #13
Opened 2024-09-03 13:38 UTC by kriazantseva

2024-09-04 14:12 UTC, Elena-Bruyako requested changes
see comments

2024-09-04 14:12 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstoreapp/controller/OrderController.java
> +    public void updateOrderStatus(@PathVariable Long orderId,
```suggestion
    public OrderDto updateOrderStatus(@PathVariable Long orderId,
```

2024-09-04 14:12 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstoreapp/controller/ShoppingCartController.java
> +    public void makeOrder(
all logic related to order should be in OrderController

2024-09-04 14:12 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstoreapp/dto/order/CreateOrderRequestDto.java
> +        @NotEmpty String shippingAddress
```suggestion
        @NotBlank String shippingAddress
```

2024-09-04 14:12 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstoreapp/dto/orderitem/CreateOrderItemRequestDto.java
> +public record CreateOrderItemRequestDto(
Where do you use this dto?

2024-09-04 14:12 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstoreapp/model/CartItem.java
> +@EqualsAndHashCode
```suggestion
```

2024-09-04 14:12 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstoreapp/model/CartItem.java
>  public class CartItem {
add `@ManyToOne(fetch = FetchType.LAZY, optional = false)` for private ShoppingCart shoppingCart;

2024-09-04 14:12 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstoreapp/model/Order.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-09-04 14:12 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstoreapp/model/Order.java
> +    private Status status;
```suggestion
    private Status status = Status.PENDING;
```

you can initialize it straightaway

2024-09-04 14:12 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstoreapp/model/Order.java
> +    )
```suggestion
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true)
```

2024-09-04 14:12 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstoreapp/model/Order.java
> +    @Column(name = "shipping_address", nullable = false)
```suggestion
    @Column(nullable = false)
```

2024-09-04 14:12 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstoreapp/model/Order.java
> +    @Column(name = "order_date", nullable = false)
```suggestion
    @Column(nullable = false)

```

2024-09-04 14:12 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstoreapp/model/OrderItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-09-04 14:12 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstoreapp/service/impl/OrderServiceImpl.java
> +        throw new EntityNotFoundException("Item with id: " + orderItemId + " had no order items");
```suggestion
        OrderItem orderItem = itemRepository.findByIdAndOrderIdAndUserId(orderItemId, orderId, userId).orElseThrow(() -> new EntityNotFoundException("Item with id: " + orderItemId + " had no order items");
        throw new EntityNotFoundException("Item with id: " + orderItemId + " had no order items");
        return orderItemMapper.toDto(orderItem);
```

2024-09-04 14:12 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstoreapp/service/impl/OrderServiceImpl.java
> +    public OrderDto getOrdersByUserId(Long userId) {
```suggestion
    public OrderDto getOrderByUserId(Long userId) {
```

2024-09-04 14:12 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstoreapp/service/impl/OrderServiceImpl.java
> +
add getAllOrders method

2024-09-04 14:12 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstoreapp/service/impl/ShoppingCartServiceImpl.java
> +        Order order = orderMapper.toEntity(requestDto);
create method createOrder in OrderServiceImpl and implement it there 
as I understood these logic related to the create order

2024-09-04 14:12 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstoreapp/service/impl/OrderServiceImpl.java
> +@Transactional
should we use this annotation for all methods in service?

2024-09-05 19:37 UTC, sarakhmen approved these changes

2024-09-08 13:33 UTC, merged