tests for books and categories
kriazantseva/book-store-app pull request #15
Opened 2024-10-01 16:37 UTC by kriazantseva

![coverage](https://github.com/user-attachments/assets/2b3b3cf3-5cde-4168-8cf2-9926ee9d995c)

2024-10-02 09:49 UTC, MentorMateAcademy requested changes

2024-10-02 09:49 UTC, MentorMateAcademy commented on src/test/java/mate/academy/bookstoreapp/controller/BookControllerTest.java
> +        assertEquals("Arthur Conan Doyle", book.author());
Please save to constants and reuse it

2024-10-02 09:49 UTC, MentorMateAcademy commented on src/test/java/mate/academy/bookstoreapp/controller/BookControllerTest.java
> +                List.of(1L)
I see duplication of code, let`s create private method with building this entity

2024-10-02 09:49 UTC, MentorMateAcademy commented on src/test/java/mate/academy/bookstoreapp/controller/BookControllerTest.java
> +                List.of(1L)
and feel free to use constants for values

2024-10-02 09:49 UTC, MentorMateAcademy commented on src/test/java/mate/academy/bookstoreapp/controller/BookControllerTest.java
> +        LOGGER.info("Response content: " + content);
why do you need logger in tests?

2024-10-02 09:49 UTC, MentorMateAcademy commented on src/test/java/mate/academy/bookstoreapp/service/CategoryServiceTest.java
> +
"when" should be before action

2024-10-03 13:05 UTC, Elena-Bruyako commented on src/test/java/mate/academy/bookstoreapp/controller/BookControllerTest.java
> +        LOGGER.info("Response content: " + content);
Fix comment

2024-10-03 13:17 UTC, Elena-Bruyako requested changes
fix previous comment https://github.com/kriazantseva/book-store-app/pull/15#discussion_r1784167114

2024-10-03 14:29 UTC, Elena-Bruyako approved these changes

2024-10-03 16:31 UTC, merged