custom globalExceptionHandler and data validation
kriazantseva/book-store-app pull request #6
Opened 2024-06-09 09:59 UTC by kriazantseva

2024-06-09 11:45 UTC, MentorMateAcademy requested changes

2024-06-09 11:45 UTC, MentorMateAcademy commented on src/main/java/mate/academy/bookstoreapp/dto/CreateBookRequestDto.java
> +        @NotNull @Min(0) BigDecimal price,
```suggestion
        @NotNull @Positive BigDecimal price,

```

2024-06-09 11:45 UTC, MentorMateAcademy commented on src/main/java/mate/academy/bookstoreapp/dto/CreateBookRequestDto.java
> +        @NotNull String author,
Maybe better NoEmpty?

2024-06-09 11:45 UTC, MentorMateAcademy commented on src/main/java/mate/academy/bookstoreapp/dto/CreateBookRequestDto.java
>          String description,
You can validate description

2024-06-09 11:45 UTC, MentorMateAcademy commented on src/main/java/mate/academy/bookstoreapp/exceptions/CustomGlobalExceptionHandler.java
> +            String fieldName = ((FieldError) error).getField();
```suggestion
        if (error instanceof FieldError fieldError) {
            String fieldName = fieldError.getField();

```

2024-06-09 11:45 UTC, MentorMateAcademy commented on src/main/java/mate/academy/bookstoreapp/exceptions/CustomGlobalExceptionHandler.java
> +            String fieldName = ((FieldError) error).getField();
Try to use new features of java

2024-06-10 06:34 UTC, Elena-Bruyako requested changes
Let's fix some comments

2024-06-10 06:34 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstoreapp/dto/CreateBookRequestDto.java
> +        @NotEmpty String title,
```suggestion
        @NotBlank String title,
```
For String fields

2024-06-10 06:34 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstoreapp/dto/CreateBookRequestDto.java
> +        @NotNull @Isbn String isbn,
```suggestion
        @NotBlank @Isbn String isbn,

```

2024-06-10 06:34 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstoreapp/dto/CreateBookRequestDto.java
> +        @NotEmpty String author,
```suggestion
        @NotBlank String author,

```

2024-06-10 09:50 UTC, okuzan approved these changes

2024-06-11 10:59 UTC, merged