added user entity and authentication
kriazantseva/book-store-app pull request #8
Opened 2024-06-14 17:41 UTC by kriazantseva

2024-06-14 19:45 UTC, sarakhmen requested changes
You did a lot of extra work in this HW. And that's not good that you don't follow a specification. Please read the task description once again and provide a solution following requiremets

2024-06-15 05:21 UTC, Elena-Bruyako requested changes
Good job! Let's fix some comments

2024-06-15 05:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstoreapp/exceptions/CustomGlobalExceptionHandler.java
> +        return new ResponseEntity<>(body, HttpStatus.BAD_REQUEST);
```suggestion
        return new ResponseEntity<>(body, HttpStatus.CONFLICT);

```

2024-06-15 05:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstoreapp/repository/user/UserRepository.java
> +    Optional<User> findByEmail(String email);
It's better to use this method to avoid calling isPresent() in Service
```suggestion
    boolean existsByEmail(String email);
```

2024-06-15 05:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstoreapp/service/impl/UserServiceImpl.java
> +        user.setEmail(requestDto.email());
Look like Mapper logic

2024-06-15 05:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstoreapp/validation/FieldMatchValidation.java
> +        if (firstObj != null) {
```suggestion
       return Objects.equals(firstObj, secondObj);
```

2024-06-15 05:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstoreapp/validation/FieldMatchValidation.java
> +
```suggestion

```

2024-06-17 16:39 UTC, Vasul-Pankiv approved these changes

2024-06-17 16:39 UTC, Vasul-Pankiv commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/02-create-user-table.yml
add empty line to the end of file

2024-06-17 17:10 UTC, merged